name: update-monthly

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 1 * *"

jobs:
  build:
    if: github.repository == 'yfiua/index-constituents'

    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: pip-install
      run: pip install -r requirements.txt
    - name: update-data
      run: ./update-monthly.sh
    - name: update-timestamp
      run: ./update-timestamp.sh
    - uses: stefanzweifel/git-auto-commit-action@v4
